//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooZoo.Components.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListAnimal
    {
        public int ID { get; set; }
        public Nullable<int> AnimalId { get; set; }
        public Nullable<int> ZooId { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual ZooCompany ZooCompany { get; set; }
    }
}
